import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToggleButton from "./components/toggleButton";
import { ThemeProvider } from "./utils/themeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className="min-h-full m-0 p-0 text-darkBlueText dark:text-white bg-lightGray dark:bg-darkBlueBG"
      lang="en"
    >
      <body className="min-h-full m-0 p-0">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-between items-center w-full py-lg px-screen bg-white dark:bg-blue shadow-md">
            <h1 className="text-2xl flex flex-col md:flex-row font-bold">
              Where in the world?
            </h1>
            <div className="flex items-center h-fit">
              <ToggleButton />
            </div>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
